modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "theatricalextralights"
version = "${version}"
displayName = "Theatrical: Extra Lights"
authors = "dumann089, Rushmead, J8-Diablo"
description = '''
Addon for Theatrical - moving heads, LED panels, PARs, water jets, pyro, lasers, and more stage lighting fixtures with DMX / Art-Net support.
'''
#logoFile = ""

[[mixins]]
config = "theatricalextralights-common.mixins.json"

[[dependencies.theatricalextralights]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.theatricalextralights]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.theatricalextralights]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.theatricalextralights]]
modId = "theatrical"
type = "required"
versionRange = "[1.0.0-alpha.23,)"
ordering = "AFTER"
side = "BOTH"
